import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PortfolioNavbar from "@/components/ui/Navbar"
import Footer from "@/components/ui/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vishesh Kr. Gautam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-red text-foreground">
      <header className="sticky top-0 z-50 bg-background">
        <PortfolioNavbar/>
        </header>
        {children}

        <Footer/>
        </body>
      {/* <body className="min-h-full flex flex-col bg-red-500 text-white">{children}</body> */}
    </html>
  );
}
